sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t rush3003/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rush3003/docker-react npm run test
